name: "Validate Action"
inputs:
  type:
    required: true
    type: string
    default: validate
  target_folder:
    required: true
    type: string
  schema_name:
    required: true
    type: string
  db_name:
    required: true
    type: string
  sf_user:
    required: true
    type: string
  sf_password:
    required: true
    type: string
  sf_role:
    required: true
    type: string
    default: EDA_DEPLOY_ROLE
  sf_account:
    required: true
    type: string

runs:
  using: composite
  steps:
    - name: check_vars
      run: |
        echo ${{ inputs.target_folder }}
        echo ${{ inputs.db_name }}
        echo ${{ inputs.schema_name }}
        echo ${{ inputs.sf_password }}
        echo ${{ inputs.sf_account }}
        echo ${{ inputs.type }}
        echo ${{ inputs.sf_role }}
      shell: bash
